[project]
name = 'usdcx-streamer'
description = 'Continuous payment streaming for USDCx'
authors = ['ghislo.btc']
telemetry = false
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SP120SBRBQJ00MCWS7TM5R8WJNTTKD5K0HFRC2CNE.usdcx'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST30J9EZKY44SS1EBT8XNKJFA77Z4TSDBEMZ55MEJ.precious-white-sparrow'

[contracts.mock-usdcx_clar]
path = 'contracts/mock-usdcx_clar.clar'
clarity_version = 3
epoch = 'latest'

[contracts.payment-stream_clar]
path = 'contracts/payment-stream_clar.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
